import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { toast } from "react-hot-toast";

export default function Home() {
  const [list, setList] = useState([]);

  async function fullList() {
    try {
      fetch("https://jsonplaceholder.typicode.com/todos")
        .then((response) => response.json())
        .then((data) => {
          setList(data);
        });
    } catch (error: any) {
      toast.error(error);
    }
  }

  useEffect(() => {
    fullList();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {list.map((eachContent: any) => (
          <li key={eachContent.id}>{eachContent.title}</li>
        ))}
      </main>
    </>
  );
}
